// app/layout.tsx
import type { Metadata } from 'next';
import './globals.css';
import { Suspense } from 'react';
import { UserProvider } from './_lib/UserContext';
import { headers } from 'next/headers';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

async function getUser() {
  const headersList = await headers(); // Await headers()
  const userHeader = headersList.get('x-user'); // Now get() is available
  if (userHeader) {
    return JSON.parse(userHeader) as { id: string; name: string; email: string };
  }
  return null; // Middleware should redirect, so this is a fallback
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getUser();

  return (
    <html lang="en">
      <body>
        <UserProvider user={user}>
          <Suspense fallback={<Loading />}>
            <div>{children}</div>
          </Suspense>
        </UserProvider>
      </body>
    </html>
  );
}

function Loading() {
  return (
    <div
      style={{
        width: '100vw',
        height: '100vh',
        backgroundColor: 'green',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        textAlign: 'center',
      }}
    >
      Loading Layout...
    </div>
  );
}